# census_exports.R -- WHO USES EACH EXPORTED NAME, AND WAS IT EVER RELEASED?
#
# WHY THIS FILE EXISTS. Every "this export has no caller" / "this one is free to delete" claim in the
# Phase 19p review and the Phase 20 plan was DERIVED by hand, and two of them were derived WRONG
# (`tab_md_css()` was filed as released when it is in neither v1.2.0 nor CRAN 1.3.1; nine live
# exports were reported as having zero callers). This script makes the census re-measurable instead
# of re-derived, and encodes the two traps that produced those errors:
#
#   TRAP 1  LC_ALL=C. The dev box is fr_FR.UTF-8, whose collation does NOT group identifiers
#           containing `_` / `.`, so a sort|uniq|comm census silently mis-pairs names. This script
#           does every set operation in R, on plain character vectors, so the locale cannot reach it.
#   TRAP 2  never `grep -w` on a pattern ending in `(`. `\b` does not match between `r` and `(`, so
#           `grep -w "tab_ci("` finds nothing. The call pattern used here is
#           `(^|[^a-zA-Z0-9._])<name>\(`, which is also what refuses `set_num` inside `jmv_set_num`.
#
# WHAT IT COUNTS, per exported name:
#   released  "1.2.0" / "1.3.1" / "dev"  -- the DELETE-vs-DEPRECATE decision. The only git tag is
#             v1.2.0 (two releases old); the CRAN 1.3.1 snapshot is commit 86320287. A name absent
#             from BOTH is unreleased and free to delete; a name in either takes a deprecation.
#   R         call sites in R/ OUTSIDE its own definition file, comment lines dropped
#   R_own     call sites in its own definition file (self-recursion, methods, examples)
#   tests / vignettes / readme / dev
#   rd        lines of the man/*.Rd that carries its \alias, and whether that page is \keyword{internal}
#   pkgdown   the _pkgdown.yml section listing it ("" = not in the reference index)
#
# HOW TO USE IT, around a phase that changes the export surface:
#   Rscript dev/census_exports.R save  [file.rds]   # before
#   Rscript dev/census_exports.R check [file.rds]   # after -- prints the delta, or IDENTICAL
#   Rscript dev/census_exports.R                    # just print today's census
#
# It needs NO devtools::load_all(): everything is read off NAMESPACE, the sources and git, so it is
# fast and cannot be perturbed by the package's own load-time code.

`%||%` <- function(x, y) if (is.null(x)) y else x

# Run from the package root (the other dev/verify_*.R scripts assume the same).
root <- if (dir.exists("R") && file.exists("NAMESPACE")) "." else "~/github/tabxplor"

# --- the exported names ------------------------------------------------------------------------
# NAMESPACE is generated by roxygen2, one `export(name)` per line; a quoted name (`"%>%"`,
# `"fmt_attr<-"`) keeps its quotes, which are stripped here.
ns_exports <- function(lines) {
  e <- grep("^export\\(", lines, value = TRUE)
  e <- sub("^export\\(", "", sub("\\)\\s*$", "", e))
  sort(gsub('^"|"$', "", e))
}

exports_now <- ns_exports(readLines(file.path(root, "NAMESPACE"), warn = FALSE))

git_ns <- function(rev) {
  out <- suppressWarnings(system2("git", c("-C", shQuote(root), "show", paste0(rev, ":NAMESPACE")),
                                  stdout = TRUE, stderr = FALSE))
  if (!length(out) || !is.null(attr(out, "status"))) character(0) else ns_exports(out)
}
exp_120 <- git_ns("v1.2.0")        # the only tag
exp_131 <- git_ns("86320287")      # the CRAN 1.3.1 snapshot -- the real released baseline

released_of <- function(nm) {
  if (nm %in% exp_120) "1.2.0" else if (nm %in% exp_131) "1.3.1" else "dev"
}

# --- the corpus --------------------------------------------------------------------------------
# `code_only`: drop full-line comments (roxygen included). An inline trailing comment is left alone
# -- a call before a `#` on the same line is a real call.
read_code <- function(path) {
  L <- readLines(path, warn = FALSE)
  L[!grepl("^\\s*#", L)]
}
files_in <- function(dir, pat) {
  d <- file.path(root, dir)
  if (!dir.exists(d)) character(0) else list.files(d, pattern = pat, full.names = TRUE, recursive = TRUE)
}

r_files    <- setdiff(files_in("R", "[.]R$"), files_in("R", "[.]h[.]R$"))   # *.h.R are generated
test_files <- files_in("tests", "[.]R$")
vig_files  <- files_in("vignettes", "[.](Rmd|R)$")
dev_files  <- files_in("dev", "[.]R$")
readme     <- file.path(root, "README.Rmd")
readme     <- if (file.exists(readme)) readme else character(0)

corpus <- function(fs) stats::setNames(lapply(fs, read_code), fs)
C_R <- corpus(r_files); C_T <- corpus(test_files); C_V <- corpus(vig_files)
C_D <- corpus(dev_files); C_M <- corpus(readme)

# `%>%`, `fmt_attr<-`, `[.tabxplor_tab` -- an export name is not always a plain identifier.
re_esc  <- function(x) gsub("([][(){}.^$|*+?\\\\])", "\\\\\\1", x)
call_re <- function(nm) paste0("(^|[^a-zA-Z0-9._])", re_esc(nm), "\\(")

count_in <- function(cp, nm, exclude = character(0)) {
  re <- call_re(nm)
  sum(vapply(names(cp), function(f) if (f %in% exclude) 0L else sum(grepl(re, cp[[f]], perl = TRUE)),
             integer(1)))
}

# The file that DEFINES a name -- so its own methods/examples are reported apart from real callers.
def_file <- function(nm) {
  re <- paste0("^\\s*`?", re_esc(nm), "`?\\s*(<-|=)\\s")
  hit <- names(C_R)[vapply(names(C_R), function(f) any(grepl(re, C_R[[f]], perl = TRUE)), logical(1))]
  if (length(hit)) hit[[1]] else NA_character_
}

# --- man/ --------------------------------------------------------------------------------------
rd_files <- list.files(file.path(root, "man"), pattern = "[.]Rd$", full.names = TRUE)
rd_index <- do.call(rbind, lapply(rd_files, function(f) {
  L <- readLines(f, warn = FALSE)
  al <- gsub("^\\\\alias\\{|\\}\\s*$", "", grep("^\\\\alias\\{", L, value = TRUE))
  if (!length(al)) return(NULL)
  data.frame(alias = al, rd = basename(f), rd_lines = length(L),
             internal = any(grepl("^\\\\keyword\\{internal\\}", L)), stringsAsFactors = FALSE)
}))

# --- _pkgdown.yml ------------------------------------------------------------------------------
# Deliberately a line scan, not a YAML parse: the file is hand-written with `- title:` / `contents:`
# blocks and no anchors, and a parser would pull in yaml as a dev dependency for one field.
pkgdown_section <- local({
  p <- file.path(root, "_pkgdown.yml")
  if (!file.exists(p)) return(function(nm) "")
  L <- readLines(p, warn = FALSE)
  sec <- ""; map <- character(0)
  for (l in L) {
    if (grepl("^-\\s*title:", l)) sec <- trimws(sub("^-\\s*title:\\s*", "", l))
    else if (grepl("^\\s*-\\s+[a-zA-Z._][a-zA-Z0-9._]*\\s*$", l) && nzchar(sec))
      map[trimws(sub("^\\s*-\\s+", "", l))] <- sec
  }
  function(nm) unname(map[nm] %||% "")[1]
})

# --- the census --------------------------------------------------------------------------------
census <- function() {
  rows <- lapply(exports_now, function(nm) {
    own <- def_file(nm)
    rd  <- if (is.null(rd_index)) NULL else rd_index[rd_index$alias == nm, , drop = FALSE]
    s   <- pkgdown_section(nm)
    data.frame(
      name      = nm,
      released  = released_of(nm),
      R         = count_in(C_R, nm, exclude = if (is.na(own)) character(0) else own),
      R_own     = if (is.na(own)) 0L else count_in(C_R[own], nm),
      tests     = count_in(C_T, nm),
      vignettes = count_in(C_V, nm),
      readme    = count_in(C_M, nm),
      dev       = count_in(C_D, nm),
      rd        = if (NROW(rd)) rd$rd[[1]]       else NA_character_,
      rd_lines  = if (NROW(rd)) rd$rd_lines[[1]] else NA_integer_,
      internal  = if (NROW(rd)) rd$internal[[1]] else NA,
      pkgdown   = if (is.na(s)) "" else s,
      stringsAsFactors = FALSE
    )
  })
  do.call(rbind, rows)
}

# --- main --------------------------------------------------------------------------------------
args <- commandArgs(trailingOnly = TRUE)
mode <- if (length(args) >= 1) args[[1]] else "print"
path <- if (length(args) >= 2) args[[2]] else "/tmp/tabxplor_exports.rds"

got <- census()
cat("exports:", nrow(got), " (1.2.0:", sum(got$released == "1.2.0"),
    " 1.3.1:", sum(got$released == "1.3.1"), " dev:", sum(got$released == "dev"), ")",
    " man/ total:", sum(rd_index$rd_lines[!duplicated(rd_index$rd)]), "lines\n")

if (identical(mode, "save")) {
  saveRDS(got, path, version = 2)
  cat("saved to", path, "\n")
} else if (identical(mode, "check")) {
  ref <- readRDS(path)
  gone <- setdiff(ref$name, got$name); new <- setdiff(got$name, ref$name)
  common <- intersect(ref$name, got$name)
  a <- ref[match(common, ref$name), ]; z <- got[match(common, got$name), ]
  diff_cols <- lapply(setdiff(names(got), "name"), function(cn) {
    w <- which(!mapply(identical, a[[cn]], z[[cn]]))
    if (!length(w)) NULL else data.frame(name = common[w], field = cn,
                                         was = as.character(a[[cn]][w]),
                                         now = as.character(z[[cn]][w]),
                                         stringsAsFactors = FALSE)
  })
  d <- do.call(rbind, diff_cols)
  if (!length(gone) && !length(new) && is.null(d)) {
    cat("IDENTICAL -- ", length(common), " exports, every count and every Rd unchanged.\n")
  } else {
    if (length(gone)) cat("REMOVED exports:", paste(gone, collapse = ", "), "\n")
    if (length(new))  cat("NEW exports    :", paste(new,  collapse = ", "), "\n")
    if (!is.null(d)) {
      cat("CHANGED in", nrow(d), "field(s):\n")
      print(d[order(d$name), ], row.names = FALSE)
    }
  }
} else {
  # the readings the Phase 20 plan asks for, printed rather than saved
  zero <- got[got$R == 0 & got$tests == 0 & got$vignettes == 0 & got$readme == 0, ]
  cat("\n-- exported, no caller anywhere (R/ tests/ vignettes/ README) --\n")
  print(zero[, c("name", "released", "dev", "rd_lines", "pkgdown")], row.names = FALSE)
  cat("\n-- exported, untaught (no vignette and no README) --", nrow(
    got[got$vignettes == 0 & got$readme == 0, ]), "of", nrow(got), "\n")
  cat("\n-- the 15 biggest man/ pages --\n")
  u <- got[!is.na(got$rd_lines) & !duplicated(got$rd), ]
  print(utils::head(u[order(-u$rd_lines), c("name", "rd", "rd_lines", "released")], 15), row.names = FALSE)
}
