# PURPOSE: dump every footer legend tabxplor can compose, as MARKDOWN, for a manual read-through.
# ROLE: the acceptance artefact of Phase 22f-i (the footer-legend rewrite). Not a test: it asserts
#   nothing, it just puts every combination side by side so wording problems are visible at a glance.
# KEY CONSTRAINTS:
#   - Every block is rendered in EN and FR, and under each palette that changes the WORDS
#     (a colour palette names no direction; the publication ones name their faces).
#   - `medium = "plain"` on purpose: this reviews the SENTENCES. Colour and face are reviewed in the
#     html/Excel exports.
#   - IT WRITES MARKDOWN, and the maintainer annotates it in place: a regeneration must not undo the
#     structure they read it in. The annotations live in the git diff, so keep the layout stable.
# Usage:  OMP_NUM_THREADS=1 Rscript dev/review_manual/legend_review.R
#         -> dev/review_manual/legend_review.md

suppressMessages(devtools::load_all("~/github/tabxplor", quiet = TRUE))
suppressMessages(library(dplyr))

OUT    <- "~/github/tabxplor/dev/review_manual/legend_review.md"
LANGS  <- c("en", "fr")
THEMES <- c("light", "dark", "print_minimalistic", "print_emphasis", "print_marks")

d <- suppressWarnings(gss_cat_data_formatting())
d <- d |> mutate(w = 1 + (as.integer(race) %% 3) / 2)

con <- file(path.expand(OUT), open = "wt", encoding = "UTF-8")
on.exit(close(con), add = TRUE)
say <- function(...) cat(..., "\n", sep = "", file = con)

# every footer line of one table (weight + Model: + interactions + colour legend + stars), which is
# what an export actually prints -- not the colour legend alone.
footer <- function(x, lang, theme)
  render_footer(tab_footer_streams(x, style = "prose", lang = lang, theme = theme),
                medium = "plain", theme = theme)

# one CASE = one table, shown across languages and (only where they differ) across palettes.
case <- function(title, call, themes = c("light", "print_minimalistic", "print_emphasis", "print_marks")) {
  say("\n")
  say("### ", title)
  say("")
  x <- tryCatch(suppressMessages(suppressWarnings(force(call))),
                error = function(e) { say("!! ", conditionMessage(e)); NULL })
  if (is.null(x)) return(invisible())
  for (th in themes) {
    for (lg in LANGS) {
      ln <- tryCatch(footer(x, lg, th), error = function(e) paste("!!", conditionMessage(e)))
      if (!length(ln)) next
      say("\n- ", th, " / ", lg)
      for (l in ln) say("  ", l)
    }
  }
  invisible()
}

say("# tabxplor footer legends --- manual review (Phase 22f-i)")
say("")
say("Generated by `dev/review_manual/legend_review.R`. One block per case, EN + FR, under the colour")
say("palette and the three publication ones. Flag a wanted change by adding a `- I want: \"...\"` line")
say("under the rendering it applies to; the diff against the last commit is the change list.")

# ============================================================================ crosstabs, the measures
say("\n\n## CROSSTABS")

case("pct = 'row', color = TRUE (diff + ratio background), ignore",
     tab(d, "rincome", "marital", pct = "row", color = TRUE))
case("pct = 'row', grey_non_signif",
     tab(d, "rincome", "marital", pct = "row", color = TRUE, color_signif = "grey_non_signif"))
case("pct = 'row', guaranteed_effect",
     tab(d, "rincome", "marital", pct = "row", color = TRUE, color_signif = "guaranteed_effect"))
case("pct = 'col', color = TRUE",
     tab(d, "rincome", "marital", pct = "col", color = TRUE))
case("pct = 'row', text channel only (color = 'diff')",
     tab(d, "rincome", "marital", pct = "row", color = "diff"))
case("pct = 'row', ratio on the text channel",
     tab(d, "rincome", "marital", pct = "row", color = "ratio"))
case("counts, color = 'contrib'",
     tab(d, "rincome", "marital", pct = "no", color = "contrib"))
case("counts, color = 'contrib', guaranteed_effect (the standardized residual)",
     tab(d, "rincome", "marital", pct = "no", color = "contrib",
         color_signif = "guaranteed_effect"))
case("odds ratio (color = 'or', ref = 'first')",
     tab(d, "race", "marital", pct = "row", color = "or", ref = "first"))
case("numeric column variable: means, color = TRUE (-> ratio of means)",
     tab(d, "race", "age", color = TRUE))
case("numeric column variable: means, color = 'diff' (-> standardized)",
     tab(d, "race", "age", color = "diff"))

# ------------------------------------------------------------------------------------ the reference
say("\n\n## THE REFERENCE")

case("ref = 1 -- ONE row variable (the label used to resolve)",
     tab(d, "rincome", "marital", pct = "row", color = TRUE, ref = 1))
case("ref = 1 -- TWO row variables (the label cannot resolve: the 22f-i bug)",
     tab(d, c("rincome", "age"), "marital", pct = "row", color = TRUE, ref = 1))
case("ref = 1, grey_non_signif",
     tab(d, c("rincome", "age"), "marital", pct = "row", color = TRUE, ref = 1,
         color_signif = "grey_non_signif"))
case("ref = 1, guaranteed_effect",
     tab(d, c("rincome", "age"), "marital", pct = "row", color = TRUE, ref = 1,
         color_signif = "guaranteed_effect"))
case("comp = 'all' (the reference is the TOTAL TABLE)",
     tab(d, "rincome", "marital", tab_vars = "race", pct = "row", color = TRUE, comp = "all"))
case("tab_vars (sub-tables), grey_non_signif",
     tab(d, "rincome", "marital", tab_vars = "race", pct = "row", color = TRUE,
         color_signif = "grey_non_signif"))
case("spread_vars (a spread swaps the header bands)",
     tab(d, "rincome", "marital", spread_vars = "race", pct = "row", color = TRUE))

# ------------------------------------------------------------------------------------- the interval
say("\n\n## THE INTERVAL")

case("ci_method = 'ac', conf_level = 0.9",
     tab(d, "rincome", "marital", pct = "row", color = TRUE, ci = "ref",
         color_signif = "grey_non_signif", ci_method = c(diff = "ac"), conf_level = 0.9))
case("weighted (wt =): the weight line + the legend",
     tab(d, "rincome", "marital", pct = "row", color = TRUE, wt = "w",
         color_signif = "grey_non_signif"))
case("survey design (the design-df clause)",
     { if (!requireNamespace("survey", quietly = TRUE)) stop("survey not installed")
       dz <- survey::svydesign(ids = ~1, weights = ~w, data = d)
       tab(dz, "rincome", "marital", pct = "row", color = TRUE,
           color_signif = "grey_non_signif") })
case("a column carrying NO stored ci_method (names no interval)",
     tab(d, "rincome", "marital", pct = "row", color = TRUE,
         color_signif = "grey_non_signif") |>
       mutate(across(where(is_fmt), ~ tabxplor:::set_ci_method(., ""))))

# ----------------------------------------------------------------------------------- the palette API
say("\n\n## A CUSTOM PALETTE")

old <- get("base", envir = tabxplor:::tabxplor_palette_env)
set_color_palette(text_colors = c("#111111", "#222222", "#333333", "#444444"))
case("a custom colour palette (no baked direction words either)",
     tab(d, "rincome", "marital", pct = "row", color = TRUE), themes = "light")
assign("base", old, envir = tabxplor:::tabxplor_palette_env); tabxplor:::build_palettes()

# =========================================================================================== tab_reg
say("\n\n## REGRESSIONS")

P <- c("rincome", "race", "age")

case("binomial, empirical = TRUE (the crude/adjusted pair)",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial", empirical = TRUE))
case("binomial, no empirical",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial"))
case("binomial, measure = 'ratio' (risk ratio)",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial", measure = "ratio",
             empirical = TRUE))
case("binomial, measure = 'difference', effect = 'marginal' (mRD)",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial",
             measure = "difference", effect = "marginal", empirical = TRUE))
case("binomial, effect = 'at_reference'",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial",
             effect = "at_reference", measure = "difference", empirical = TRUE))
case("poisson (IRR)",
     tab_reg(d, outcome = "tvhours", predictors = P, family = "poisson", empirical = TRUE))
case("poisson, color = 'adjustment' (the gap measure)",
     tab_reg(d, outcome = "tvhours", predictors = P, family = "poisson", color = "adjustment"))
case("binomial, color = 'adjustment' (non-collapsible -> the caveat)",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial", color = "adjustment"))
case("binomial, color = c(TRUE, 'adjustment') (effect in text, gap behind it)",
     tab_reg(d, outcome = "married", predictors = P, family = "binomial",
             color = c(TRUE, "adjustment")))
case("gaussian (mean difference)",
     tab_reg(d, outcome = "age", predictors = c("rincome", "race"), family = "gaussian",
             empirical = TRUE))
case("gaussian, conditional coefficient (raw scale)",
     tab_reg(d, outcome = "age", predictors = c("rincome", "race"), family = "gaussian",
             effect = "conditional", empirical = TRUE))
case("multinomial",
     tab_reg(d, outcome = "marital", predictors = c("rincome", "race"), family = "multinomial",
             empirical = TRUE))
case("ordinal (cumulative OR)",
     tab_reg(d, outcome = "rincome", predictors = c("race", "age"), family = "ordinal",
             empirical = TRUE))
case("two outcomes, two families",
     tab_reg(d, outcome = c("married", "tvhours"), predictors = c("race", "age"),
             family = c("binomial", "poisson"), empirical = TRUE))
case("tab_vars + color = 'between_groups' (effect modification)",
     tab_reg(d, outcome = "married", predictors = c("rincome", "age"), tab_vars = "race",
             family = "binomial", color = "between_groups"))
case("weighted regression",
     tab_reg(d, outcome = "married", predictors = c("race", "age"), family = "binomial",
             wt = "w", empirical = TRUE))

say("\n---")
say("")
say("*end*")
message("written: ", OUT)
