
# This file is automatically generated, you probably don't want to edit this

jmvtestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            test_name = "tabxplor_export_test",
            test_dir = "",
            write_detected = FALSE,
            write_all = FALSE, ...) {

            super$initialize(
                package="tabxplor",
                name="jmvtest",
                requiresData=TRUE,
                ...)

            private$..test_name <- jmvcore::OptionString$new(
                "test_name",
                test_name,
                default="tabxplor_export_test")
            private$..test_dir <- jmvcore::OptionString$new(
                "test_dir",
                test_dir,
                default="")
            private$..write_detected <- jmvcore::OptionAction$new(
                "write_detected",
                write_detected)
            private$..write_all <- jmvcore::OptionAction$new(
                "write_all",
                write_all)

            self$.addOption(private$..test_name)
            self$.addOption(private$..test_dir)
            self$.addOption(private$..write_detected)
            self$.addOption(private$..write_all)
        }),
    active = list(
        test_name = function() private$..test_name$value,
        test_dir = function() private$..test_dir$value,
        write_detected = function() private$..write_detected$value,
        write_all = function() private$..write_all$value),
    private = list(
        ..test_name = NA,
        ..test_dir = NA,
        ..write_detected = NA,
        ..write_all = NA)
)

jmvtestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtestResults",
    inherit = jmvcore::Group,
    active = list(
        environment = function() private$.items[["environment"]],
        documents = function() private$.items[["documents"]],
        fallbacks = function() private$.items[["fallbacks"]],
        write_results = function() private$.items[["write_results"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Export folder test")
            self$add(jmvcore::Html$new(
                options=options,
                name="environment",
                title="Environment"))
            self$add(jmvcore::Html$new(
                options=options,
                name="documents",
                title="Documents-detection methods"))
            self$add(jmvcore::Html$new(
                options=options,
                name="fallbacks",
                title="Fallback save locations"))
            self$add(jmvcore::Html$new(
                options=options,
                name="write_results",
                title="Write results"))}))

jmvtestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tabxplor",
                name = "jmvtest",
                version = c(1,0,0),
                options = options,
                results = jmvtestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Export folder test
#'
#' 
#' @param data A data.frame (unused; the diagnostic needs no variables and
#'   runs as soon as it is added).
#' @param test_name The bare name (no extension) of the .md test file written
#'   by the buttons.
#' @param test_dir An optional extra folder to also try writing the test file
#'   into (blank = ignore).
#' @param write_detected Press to write the .md test file to the best-detected
#'   Documents folder.
#' @param write_all Press to write a distinct .md test file into every
#'   detection + fallback candidate folder.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$environment} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$documents} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fallbacks} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$write_results} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
jmvtest <- function(
    data,
    test_name = "tabxplor_export_test",
    test_dir = "",
    write_detected = FALSE,
    write_all = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvtest requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jmvtestOptions$new(
        test_name = test_name,
        test_dir = test_dir,
        write_detected = write_detected,
        write_all = write_all)

    analysis <- jmvtestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

