
# This file is automatically generated, you probably don't want to edit this

jmvtabregOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabregOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            predictors = NULL,
            split_var = NULL,
            wt = NULL,
            depFamily = NULL,
            depModelLevel = NULL,
            depTrials = NULL,
            exponentiate = TRUE,
            effect = "coefficient",
            at = "average",
            empirical = FALSE,
            models = NULL,
            baseline = 1,
            compare = "none",
            na = "drop_by_model",
            refLevels = NULL,
            multiplicator = NULL,
            conf_level = 0.95,
            method = "wald",
            stars = TRUE,
            color = TRUE,
            color_signif = "grey_non_signif",
            estimate_display = "value",
            cleannames = TRUE,
            subtext = "",
            wrap_rows = 35,
            wrap_cols = 15,
            ids = NULL,
            strata = NULL,
            fpc = NULL,
            nest = FALSE,
            export_format = "excel",
            exportExcel = FALSE,
            export_dir = "~/Documents",
            export_filename = "Regression",
            resetPath = FALSE,
            xl_replace = FALSE, ...) {

            super$initialize(
                package="tabxplor",
                name="jmvtabreg",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariables$new(
                "dependent",
                dependent,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..predictors <- jmvcore::OptionVariables$new(
                "predictors",
                predictors,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..split_var <- jmvcore::OptionVariable$new(
                "split_var",
                split_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..wt <- jmvcore::OptionVariable$new(
                "wt",
                wt,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..depFamily <- jmvcore::OptionArray$new(
                "depFamily",
                depFamily,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "depFamily",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "family",
                            NULL))))
            private$..depModelLevel <- jmvcore::OptionArray$new(
                "depModelLevel",
                depModelLevel,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "depModelLevel",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "level",
                            NULL))))
            private$..depTrials <- jmvcore::OptionArray$new(
                "depTrials",
                depTrials,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "depTrials",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "n",
                            NULL))))
            private$..exponentiate <- jmvcore::OptionBool$new(
                "exponentiate",
                exponentiate,
                default=TRUE)
            private$..effect <- jmvcore::OptionList$new(
                "effect",
                effect,
                options=list(
                    "coefficient",
                    "ame"),
                default="coefficient")
            private$..at <- jmvcore::OptionList$new(
                "at",
                at,
                options=list(
                    "average",
                    "reference"),
                default="average")
            private$..empirical <- jmvcore::OptionBool$new(
                "empirical",
                empirical,
                default=FALSE)
            private$..models <- jmvcore::OptionArray$new(
                "models",
                models,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "models",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionArray$new(
                            "vars",
                            NULL,
                            template=jmvcore::OptionVariable$new(
                                "vars",
                                NULL)))))
            private$..baseline <- jmvcore::OptionInteger$new(
                "baseline",
                baseline,
                hidden=TRUE,
                min=1,
                default=1)
            private$..compare <- jmvcore::OptionList$new(
                "compare",
                compare,
                options=list(
                    "none",
                    "baseline",
                    "sequential"),
                default="none")
            private$..na <- jmvcore::OptionList$new(
                "na",
                na,
                options=list(
                    "drop_by_model",
                    "drop_all_models"),
                default="drop_by_model")
            private$..refLevels <- jmvcore::OptionArray$new(
                "refLevels",
                refLevels,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "refLevels",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "ref",
                            NULL))))
            private$..multiplicator <- jmvcore::OptionArray$new(
                "multiplicator",
                multiplicator,
                hidden=TRUE,
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "multiplicator",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionString$new(
                            "k",
                            NULL))))
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=0.5,
                max=0.999,
                default=0.95)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "wald",
                    "profile"),
                default="wald")
            private$..stars <- jmvcore::OptionBool$new(
                "stars",
                stars,
                default=TRUE)
            private$..color <- jmvcore::OptionBool$new(
                "color",
                color,
                default=TRUE)
            private$..color_signif <- jmvcore::OptionList$new(
                "color_signif",
                color_signif,
                options=list(
                    "grey_non_signif",
                    "ignore",
                    "guaranteed_effect"),
                default="grey_non_signif")
            private$..estimate_display <- jmvcore::OptionList$new(
                "estimate_display",
                estimate_display,
                options=list(
                    "value",
                    "ci",
                    "prob",
                    "ame"),
                default="value")
            private$..cleannames <- jmvcore::OptionBool$new(
                "cleannames",
                cleannames,
                default=TRUE)
            private$..subtext <- jmvcore::OptionString$new(
                "subtext",
                subtext,
                default="",
                hidden=TRUE)
            private$..wrap_rows <- jmvcore::OptionNumber$new(
                "wrap_rows",
                wrap_rows,
                min=0,
                default=35)
            private$..wrap_cols <- jmvcore::OptionNumber$new(
                "wrap_cols",
                wrap_cols,
                min=0,
                default=15)
            private$..ids <- jmvcore::OptionVariables$new(
                "ids",
                ids,
                default=NULL)
            private$..strata <- jmvcore::OptionVariables$new(
                "strata",
                strata,
                default=NULL)
            private$..fpc <- jmvcore::OptionVariable$new(
                "fpc",
                fpc,
                default=NULL)
            private$..nest <- jmvcore::OptionBool$new(
                "nest",
                nest,
                default=FALSE)
            private$..export_format <- jmvcore::OptionList$new(
                "export_format",
                export_format,
                options=list(
                    "excel",
                    "html",
                    "md"),
                default="excel")
            private$..exportExcel <- jmvcore::OptionAction$new(
                "exportExcel",
                exportExcel)
            private$..export_dir <- jmvcore::OptionString$new(
                "export_dir",
                export_dir,
                default="~/Documents")
            private$..export_filename <- jmvcore::OptionString$new(
                "export_filename",
                export_filename,
                default="Regression")
            private$..resetPath <- jmvcore::OptionAction$new(
                "resetPath",
                resetPath)
            private$..xl_replace <- jmvcore::OptionBool$new(
                "xl_replace",
                xl_replace,
                default=FALSE)

            self$.addOption(private$..dependent)
            self$.addOption(private$..predictors)
            self$.addOption(private$..split_var)
            self$.addOption(private$..wt)
            self$.addOption(private$..depFamily)
            self$.addOption(private$..depModelLevel)
            self$.addOption(private$..depTrials)
            self$.addOption(private$..exponentiate)
            self$.addOption(private$..effect)
            self$.addOption(private$..at)
            self$.addOption(private$..empirical)
            self$.addOption(private$..models)
            self$.addOption(private$..baseline)
            self$.addOption(private$..compare)
            self$.addOption(private$..na)
            self$.addOption(private$..refLevels)
            self$.addOption(private$..multiplicator)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..method)
            self$.addOption(private$..stars)
            self$.addOption(private$..color)
            self$.addOption(private$..color_signif)
            self$.addOption(private$..estimate_display)
            self$.addOption(private$..cleannames)
            self$.addOption(private$..subtext)
            self$.addOption(private$..wrap_rows)
            self$.addOption(private$..wrap_cols)
            self$.addOption(private$..ids)
            self$.addOption(private$..strata)
            self$.addOption(private$..fpc)
            self$.addOption(private$..nest)
            self$.addOption(private$..export_format)
            self$.addOption(private$..exportExcel)
            self$.addOption(private$..export_dir)
            self$.addOption(private$..export_filename)
            self$.addOption(private$..resetPath)
            self$.addOption(private$..xl_replace)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        predictors = function() private$..predictors$value,
        split_var = function() private$..split_var$value,
        wt = function() private$..wt$value,
        depFamily = function() private$..depFamily$value,
        depModelLevel = function() private$..depModelLevel$value,
        depTrials = function() private$..depTrials$value,
        exponentiate = function() private$..exponentiate$value,
        effect = function() private$..effect$value,
        at = function() private$..at$value,
        empirical = function() private$..empirical$value,
        models = function() private$..models$value,
        baseline = function() private$..baseline$value,
        compare = function() private$..compare$value,
        na = function() private$..na$value,
        refLevels = function() private$..refLevels$value,
        multiplicator = function() private$..multiplicator$value,
        conf_level = function() private$..conf_level$value,
        method = function() private$..method$value,
        stars = function() private$..stars$value,
        color = function() private$..color$value,
        color_signif = function() private$..color_signif$value,
        estimate_display = function() private$..estimate_display$value,
        cleannames = function() private$..cleannames$value,
        subtext = function() private$..subtext$value,
        wrap_rows = function() private$..wrap_rows$value,
        wrap_cols = function() private$..wrap_cols$value,
        ids = function() private$..ids$value,
        strata = function() private$..strata$value,
        fpc = function() private$..fpc$value,
        nest = function() private$..nest$value,
        export_format = function() private$..export_format$value,
        exportExcel = function() private$..exportExcel$value,
        export_dir = function() private$..export_dir$value,
        export_filename = function() private$..export_filename$value,
        resetPath = function() private$..resetPath$value,
        xl_replace = function() private$..xl_replace$value),
    private = list(
        ..dependent = NA,
        ..predictors = NA,
        ..split_var = NA,
        ..wt = NA,
        ..depFamily = NA,
        ..depModelLevel = NA,
        ..depTrials = NA,
        ..exponentiate = NA,
        ..effect = NA,
        ..at = NA,
        ..empirical = NA,
        ..models = NA,
        ..baseline = NA,
        ..compare = NA,
        ..na = NA,
        ..refLevels = NA,
        ..multiplicator = NA,
        ..conf_level = NA,
        ..method = NA,
        ..stars = NA,
        ..color = NA,
        ..color_signif = NA,
        ..estimate_display = NA,
        ..cleannames = NA,
        ..subtext = NA,
        ..wrap_rows = NA,
        ..wrap_cols = NA,
        ..ids = NA,
        ..strata = NA,
        ..fpc = NA,
        ..nest = NA,
        ..export_format = NA,
        ..exportExcel = NA,
        ..export_dir = NA,
        ..export_filename = NA,
        ..resetPath = NA,
        ..xl_replace = NA)
)

jmvtabregResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabregResults",
    inherit = jmvcore::Group,
    active = list(
        html_table = function() private$.items[["html_table"]],
        cache_state = function() private$.items[["cache_state"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Regressions")
            self$add(jmvcore::Html$new(
                options=options,
                name="html_table",
                title="Table"))
            self$add(jmvcore::Image$new(
                options=options,
                name="cache_state",
                title="",
                width=1080,
                height=0,
                renderFun=".plot"))}))

jmvtabregBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabregBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tabxplor",
                name = "jmvtabreg",
                version = c(1,0,0),
                options = options,
                results = jmvtabregResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

#' Regressions
#'
#' 
#' @param data A data.frame.
#' @param dependent The outcome variable(s). One model is built per dependent.
#'   Set each outcome's family (and, for a binomial outcome, its modelled level
#'   or number of trials) in the Model table.
#' @param predictors The explanatory variables of the model. Factors are shown
#'   one line per level (the reference level as the neutral value); numeric
#'   predictors as a single line.
#' @param split_var A grouping variable. The same model is fitted within each
#'   of its levels and the tables are stacked (like tab_vars for crosstables).
#' @param wt A survey weight variable. Switches to design-based estimation
#'   (scale-invariant sandwich standard errors). Leave empty for unweighted
#'   results.
#' @param depFamily .
#' @param depModelLevel .
#' @param depTrials .
#' @param exponentiate Exponentiate the coefficients into ratios (odds ratios
#'   / incidence-rate ratios), automatically leaving gaussian linear
#'   coefficients on their raw scale. Uncheck to keep every coefficient on the
#'   coefficient (log / linear) scale.
#' @param effect "coefficient" is the native per-family effect (beta / OR /
#'   IRR). "AME" is the average marginal effect on the response scale (needs the
#'   marginaleffects package).
#' @param at Where marginal effects are evaluated: averaged over the sample,
#'   or at the reference profile (other predictors at their reference level /
#'   mean).
#' @param empirical Add the crude, unadjusted, single-predictor companion
#'   columns beside the model effect (the bivariate association that IS the
#'   modelised quantity with a single predictor). Binomial / gaussian / poisson
#'   only.
#' @param models .
#' @param baseline .
#' @param compare With several models (a predictor-subset list), add a
#'   likelihood-ratio / F / Wald comparison-test footer row: "baseline" tests
#'   each model against the chosen baseline model, "sequential" against the
#'   previous one (an AIC difference when not nested).
#' @param na "drop by model" fits each model / outcome on its own complete
#'   cases; "drop all models" uses one shared complete-case population across
#'   all predictors (equal N; changes the estimates), which a valid
#'   likelihood-ratio comparison test needs.
#' @param refLevels .
#' @param multiplicator .
#' @param conf_level The confidence level for intervals and the significance
#'   stars.
#' @param method Wald intervals (also the only option for weighted models) or
#'   profile-likelihood intervals (unweighted binomial / poisson only; needs
#'   MASS).
#' @param stars Show per-cell significance stars (the colours read the
#'   confidence interval either way).
#' @param color Colour the effect cells with the sensible per-family colour
#'   helper (OR magnitude for ratios, standardized difference for gaussian
#'   betas). Uncheck for no colours.
#' @param color_signif How significance interacts with the colours: grey out
#'   non-significant cells, ignore significance, or colour only the guaranteed
#'   (error-adjusted) effect.
#' @param estimate_display The estimate-cell layout. "ci" shows a visible
#'   interval; "prob" / "ame" fold the adjusted predicted probability / marginal
#'   effect into the OR cell (binomial coefficient models only).
#' @param cleannames Strip numeric prefixes from factor level labels.
#' @param subtext A free note printed below the table.
#' @param wrap_rows .
#' @param wrap_cols .
#' @param ids Cluster identifiers (survey design), largest to smallest stage.
#'   Only used with a weight; leave empty for no clustering.
#' @param strata Stratification variables (survey design). Only used with a
#'   weight.
#' @param fpc Finite-population correction (survey design). Only used with a
#'   weight.
#' @param nest Set when cluster ids are reused across strata (survey design).
#' @param export_format .
#' @param exportExcel Press to export the table to the chosen format (the
#'   button label follows the format).
#' @param export_dir The folder to save the exported file in. \code{~} expands
#'   to your home folder. Blank saves to your Documents.
#' @param export_filename The bare file name, with NO extension (the chosen
#'   format adds it). Illegal characters are removed automatically. Blank saves
#'   as "Table".
#' @param resetPath Reset the folder and file name to their defaults (your
#'   Documents folder and "Regression").
#' @param xl_replace .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$html_table} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cache_state} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jmvtabreg <- function(
    data,
    dependent = NULL,
    predictors = NULL,
    split_var = NULL,
    wt = NULL,
    depFamily = NULL,
    depModelLevel = NULL,
    depTrials = NULL,
    exponentiate = TRUE,
    effect = "coefficient",
    at = "average",
    empirical = FALSE,
    models = NULL,
    baseline = 1,
    compare = "none",
    na = "drop_by_model",
    refLevels = NULL,
    multiplicator = NULL,
    conf_level = 0.95,
    method = "wald",
    stars = TRUE,
    color = TRUE,
    color_signif = "grey_non_signif",
    estimate_display = "value",
    cleannames = TRUE,
    subtext = "",
    wrap_rows = 35,
    wrap_cols = 15,
    ids = NULL,
    strata = NULL,
    fpc = NULL,
    nest = FALSE,
    export_format = "excel",
    exportExcel = FALSE,
    export_dir = "~/Documents",
    export_filename = "Regression",
    resetPath = FALSE,
    xl_replace = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvtabreg requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(predictors)) predictors <- jmvcore::resolveQuo(jmvcore::enquo(predictors))
    if ( ! missing(split_var)) split_var <- jmvcore::resolveQuo(jmvcore::enquo(split_var))
    if ( ! missing(wt)) wt <- jmvcore::resolveQuo(jmvcore::enquo(wt))
    if ( ! missing(ids)) ids <- jmvcore::resolveQuo(jmvcore::enquo(ids))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if ( ! missing(fpc)) fpc <- jmvcore::resolveQuo(jmvcore::enquo(fpc))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(predictors), predictors, NULL),
            `if`( ! missing(split_var), split_var, NULL),
            `if`( ! missing(wt), wt, NULL),
            `if`( ! missing(ids), ids, NULL),
            `if`( ! missing(strata), strata, NULL),
            `if`( ! missing(fpc), fpc, NULL))

    for (v in split_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvtabregOptions$new(
        dependent = dependent,
        predictors = predictors,
        split_var = split_var,
        wt = wt,
        depFamily = depFamily,
        depModelLevel = depModelLevel,
        depTrials = depTrials,
        exponentiate = exponentiate,
        effect = effect,
        at = at,
        empirical = empirical,
        models = models,
        baseline = baseline,
        compare = compare,
        na = na,
        refLevels = refLevels,
        multiplicator = multiplicator,
        conf_level = conf_level,
        method = method,
        stars = stars,
        color = color,
        color_signif = color_signif,
        estimate_display = estimate_display,
        cleannames = cleannames,
        subtext = subtext,
        wrap_rows = wrap_rows,
        wrap_cols = wrap_cols,
        ids = ids,
        strata = strata,
        fpc = fpc,
        nest = nest,
        export_format = export_format,
        exportExcel = exportExcel,
        export_dir = export_dir,
        export_filename = export_filename,
        resetPath = resetPath,
        xl_replace = xl_replace)

    analysis <- jmvtabregClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

