
# This file is automatically generated, you probably don't want to edit this

jmvtabOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            row_vars = NULL,
            col_vars = NULL,
            tab_vars = NULL,
            wt = NULL,
            pct = "no",
            color = "no",
            chi2 = TRUE,
            totaltab = "line",
            na = "keep",
            lvs = "all",
            other_if_less_than = 0,
            cleannames = FALSE,
            ref = "tot",
            comp = NULL,
            ci = "auto",
            conf_level = 0.95,
            wrap_rows = 35,
            wrap_cols = 15,
            display = "auto",
            subtext = "",
            digits = 0, ...) {

            super$initialize(
                package="tabxplor",
                name="jmvtab",
                requiresData=TRUE,
                ...)

            private$..row_vars <- jmvcore::OptionVariable$new(
                "row_vars",
                row_vars,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..col_vars <- jmvcore::OptionVariables$new(
                "col_vars",
                col_vars,
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..tab_vars <- jmvcore::OptionVariables$new(
                "tab_vars",
                tab_vars,
                permitted=list(
                    "factor"),
                default=NULL)
            private$..wt <- jmvcore::OptionVariable$new(
                "wt",
                wt,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..pct <- jmvcore::OptionList$new(
                "pct",
                pct,
                options=list(
                    "no",
                    "row",
                    "col",
                    "all",
                    "all_tabs"),
                default="no")
            private$..color <- jmvcore::OptionList$new(
                "color",
                color,
                options=list(
                    "no",
                    "diff",
                    "diff_ci",
                    "after_ci",
                    "contrib",
                    "auto"),
                default="no")
            private$..chi2 <- jmvcore::OptionBool$new(
                "chi2",
                chi2,
                default=TRUE)
            private$..totaltab <- jmvcore::OptionList$new(
                "totaltab",
                totaltab,
                options=list(
                    "line",
                    "table",
                    "no"),
                default="line")
            private$..na <- jmvcore::OptionList$new(
                "na",
                na,
                options=list(
                    "keep",
                    "drop",
                    "drop_all"),
                default="keep")
            private$..lvs <- jmvcore::OptionList$new(
                "lvs",
                lvs,
                options=list(
                    "all",
                    "first",
                    "auto"),
                default="all")
            private$..other_if_less_than <- jmvcore::OptionNumber$new(
                "other_if_less_than",
                other_if_less_than,
                min=0,
                default=0)
            private$..cleannames <- jmvcore::OptionBool$new(
                "cleannames",
                cleannames,
                default=FALSE)
            private$..diff <- jmvcore::OptionList$new(
                "diff",
                diff,
                options=list(
                    "tot",
                    "first"),
                default="tot")
            private$..comp <- jmvcore::OptionList$new(
                "comp",
                comp,
                options=list(
                    "tab",
                    "all"))
            private$..ci <- jmvcore::OptionList$new(
                "ci",
                ci,
                options=list(
                    "auto",
                    "cell",
                    "diff"),
                default="auto")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                min=0,
                max=1,
                default=0.95)
            private$..wrap_rows <- jmvcore::OptionNumber$new(
                "wrap_rows",
                wrap_rows,
                min=0,
                default=35)
            private$..wrap_cols <- jmvcore::OptionNumber$new(
                "wrap_cols",
                wrap_cols,
                min=0,
                default=15)
            private$..display <- jmvcore::OptionList$new(
                "display",
                display,
                options=list(
                    "auto",
                    "n",
                    "wn",
                    "pct",
                    "diff",
                    "ctr",
                    "mean",
                    "var",
                    "ci",
                    "pct_ci",
                    "mean_ci"),
                default="auto")
            private$..subtext <- jmvcore::OptionString$new(
                "subtext",
                subtext,
                default="")
            private$..digits <- jmvcore::OptionNumber$new(
                "digits",
                digits,
                min=0,
                max=0,
                default=0)

            self$.addOption(private$..row_vars)
            self$.addOption(private$..col_vars)
            self$.addOption(private$..tab_vars)
            self$.addOption(private$..wt)
            self$.addOption(private$..pct)
            self$.addOption(private$..color)
            self$.addOption(private$..chi2)
            self$.addOption(private$..totaltab)
            self$.addOption(private$..na)
            self$.addOption(private$..lvs)
            self$.addOption(private$..other_if_less_than)
            self$.addOption(private$..cleannames)
            self$.addOption(private$..diff)
            self$.addOption(private$..comp)
            self$.addOption(private$..ci)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..wrap_rows)
            self$.addOption(private$..wrap_cols)
            self$.addOption(private$..display)
            self$.addOption(private$..subtext)
            self$.addOption(private$..digits)
        }),
    active = list(
        row_vars = function() private$..row_vars$value,
        col_vars = function() private$..col_vars$value,
        tab_vars = function() private$..tab_vars$value,
        wt = function() private$..wt$value,
        pct = function() private$..pct$value,
        color = function() private$..color$value,
        chi2 = function() private$..chi2$value,
        totaltab = function() private$..totaltab$value,
        na = function() private$..na$value,
        lvs = function() private$..lvs$value,
        other_if_less_than = function() private$..other_if_less_than$value,
        cleannames = function() private$..cleannames$value,
        diff = function() private$..diff$value,
        comp = function() private$..comp$value,
        ci = function() private$..ci$value,
        conf_level = function() private$..conf_level$value,
        wrap_rows = function() private$..wrap_rows$value,
        wrap_cols = function() private$..wrap_cols$value,
        display = function() private$..display$value,
        subtext = function() private$..subtext$value,
        digits = function() private$..digits$value),
    private = list(
        ..row_vars = NA,
        ..col_vars = NA,
        ..tab_vars = NA,
        ..wt = NA,
        ..pct = NA,
        ..color = NA,
        ..chi2 = NA,
        ..totaltab = NA,
        ..na = NA,
        ..lvs = NA,
        ..other_if_less_than = NA,
        ..cleannames = NA,
        ..diff = NA,
        ..comp = NA,
        ..ci = NA,
        ..conf_level = NA,
        ..wrap_rows = NA,
        ..wrap_cols = NA,
        ..display = NA,
        ..subtext = NA,
        ..digits = NA)
)

jmvtabResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]],
        chi2_table = function() private$.items[["chi2_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Crosstables")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Table",
                width=720,
                height=200,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="chi2_table",
                title="Chi2 Test",
                rows=0,
                columns=list(
                    list(
                        `name`="row_var", 
                        `title`="row_var", 
                        `type`="text"))))}))

jmvtabBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvtabBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "tabxplor",
                name = "jmvtab",
                version = c(1,0,0),
                options = options,
                results = jmvtabResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Crosstables
#'
#' 
#' @param data .
#' @param row_vars .
#' @param col_vars .
#' @param tab_vars .
#' @param wt .
#' @param pct .
#' @param color .
#' @param chi2 .
#' @param totaltab .
#' @param na .
#' @param lvs .
#' @param other_if_less_than .
#' @param cleannames .
#' @param diff .
#' @param comp .
#' @param ci .
#' @param conf_level .
#' @param wrap_rows .
#' @param wrap_cols .
#' @param display .
#' @param subtext .
#' @param digits .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$chi2_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$chi2_table$asDF}
#'
#' \code{as.data.frame(results$chi2_table)}
#'
#' @export
jmvtab <- function(
    data,
    row_vars = NULL,
    col_vars = NULL,
    tab_vars = NULL,
    wt = NULL,
    pct = "no",
    color = "no",
    chi2 = TRUE,
    totaltab = "line",
    na = "keep",
    lvs = "all",
    other_if_less_than = 0,
    cleannames = FALSE,
    ref = "tot",
    comp,
    ci = "auto",
    conf_level = 0.95,
    wrap_rows = 35,
    wrap_cols = 15,
    display = "auto",
    subtext = "",
    digits = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvtab requires jmvcore to be installed (restart may be required)")

    if ( ! missing(row_vars)) row_vars <- jmvcore::resolveQuo(jmvcore::enquo(row_vars))
    if ( ! missing(col_vars)) col_vars <- jmvcore::resolveQuo(jmvcore::enquo(col_vars))
    if ( ! missing(tab_vars)) tab_vars <- jmvcore::resolveQuo(jmvcore::enquo(tab_vars))
    if ( ! missing(wt)) wt <- jmvcore::resolveQuo(jmvcore::enquo(wt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(row_vars), row_vars, NULL),
            `if`( ! missing(col_vars), col_vars, NULL),
            `if`( ! missing(tab_vars), tab_vars, NULL),
            `if`( ! missing(wt), wt, NULL))

    for (v in tab_vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvtabOptions$new(
        row_vars = row_vars,
        col_vars = col_vars,
        tab_vars = tab_vars,
        wt = wt,
        pct = pct,
        color = color,
        chi2 = chi2,
        totaltab = totaltab,
        na = na,
        lvs = lvs,
        other_if_less_than = other_if_less_than,
        cleannames = cleannames,
        diff = diff,
        comp = comp,
        ci = ci,
        conf_level = conf_level,
        wrap_rows = wrap_rows,
        wrap_cols = wrap_cols,
        display = display,
        subtext = subtext,
        digits = digits)

    analysis <- jmvtabClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

